# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 09:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, default=datetime.datetime.now)),
                ('title', models.CharField(default='Empty Title', max_length=100)),
                ('body', models.TextField()),
                ('number_of_comments', models.IntegerField()),
                ('number_of_likes', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
