# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_comment_topiclike'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='url',
            field=models.CharField(auto_created=True, default='default_url', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='pub_date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='pub_date'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='number_of_comments',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='number_of_likes',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
