# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0004_topiclike_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclike',
            name='creator',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
