# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wall', '0008_remove_topiclike_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiclike',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
